### ISSUE TITLE
Exception when running espresso test

### ISSUE THREAD

**Issue by zjn0505** [didi/booster#100]
I'm still experiencing issue https://github.com/didi/booster/issues/77 when running an Espresso test.

I can reproduce with an empty Espresso test using ver. 0.24.0 upon [app-kotlin-dsl](https://github.com/boostersamples/app-kotlin-dsl)

- System version
mac OS 10.14.6
- Java version
1.8.0_171
- Gradle version
5.4.1
- Android Gradle plugin version
3.4.1
- Booster version
0.24.0
- Stack traces
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithBoosterForDebugAndroidTest'.
	...
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.didiglobal.booster.gradle.TransformInvocationKt.getVariant(TransformInvocation.kt:79)
	at com.didiglobal.booster.gradle.TransformInvocationKt.getApplicationId(TransformInvocation.kt:61)
	at com.didiglobal.booster.gradle.BoosterTransformInvocation.<init>(BoosterTransformInvocation.kt:66)
	at com.didiglobal.booster.gradle.BoosterTransform.transform(BoosterTransform.kt:28)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	... 
```

**Comment by johnsonlee** [comment]
Please try the latest snapshot version `0.25.0-SNAPSHOT`

**Comment by zjn0505** [comment]
Espresso build passed with `0.25.0`.

While when executing a simple test.
```
onView(allOf(isDisplayed(), withId(R.id.imageView))).perform(click())
```
I got the error
```
E/TestRunner: java.lang.NoSuchMethodError: No static method newOptimizedSingleThreadExecutor(Ljava/util/concurrent/ThreadFactory;Ljava/lang/String;)Ljava/util/concurrent/ExecutorService; in class Lcom/didiglobal/booster/instrument/ShadowExecutors; or its super classes (declaration of 'com.didiglobal.booster.instrument.ShadowExecutors' 
```

**Comment by johnsonlee** [comment]
> Espresso build passed with `0.25.0-SNAPSHOT`.
> 
> While when executing a simple test.
> 
> ```
> onView(allOf(isDisplayed(), withId(R.id.imageView))).perform(click())
> ```
> 
> I got the error
> 
> ```
> E/TestRunner: java.lang.NoSuchMethodError: No static method newOptimizedSingleThreadExecutor(Ljava/util/concurrent/ThreadFactory;Ljava/lang/String;)Ljava/util/concurrent/ExecutorService; in class Lcom/didiglobal/booster/instrument/ShadowExecutors; or its super classes (declaration of 'com.didiglobal.booster.instrument.ShadowExecutors' 
> ```

Please try the latest snapshot version 0.26.0-SNAPSHOT

**Comment by johnsonlee** [comment]
The [sample app project](https://github.com/boostersamples/app) has been updated, so far this issue could not be reproduced yet.

**Comment by zjn0505** [comment]
It looks that the second issue is happening when I have `minifyEnabled true` when doing espresso test. Close this issue since the main problem has been resolved.
