### ISSUE TITLE
编译打包之后运行崩溃

### ISSUE THREAD

**Issue by shenglintang** [didi/booster#133]
Please provide the following informations.

- System version 7.0

- Java version 1.8

- Gradle version 4.1

- Android Gradle plugin version 3.0.1

- Booster version 1.3.0

- Stack traces
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList[[dex file "/data/user/0/com.xinhu.steward/.00000000000/2D72A071.dex", zip file "/data/app/com.xinhu.steward-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xinhu.steward-1/lib/arm, /system/fake-libs, /data/app/com.xinhu.steward-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by johnsonlee** [comment]
在 *build/intermediates/transform/booster/* 目录下搜索一下看看是否有 * MessageProvider.class* 这个类？有可能是以独立的 class 文件存在，或者是在 JAR 文件中：

```bash
find build/intermediates/transform/booster/ -name 'MessageProvider.class'
```
或者

```bash
find build/intermediates/transform/booster/ -name '*.jar' | xargs -t -I{} unzip -I {} | grep "/MessageProvider.class"
```

**Comment by shenglintang** [comment]
目前在build/intermediates/transform/booster/目录下，没有找到* MessageProvider.class*这个类

**Comment by johnsonlee** [comment]
那可能是构建过程有问题导致这个类没有打进包里

**Comment by shenglintang** [comment]
那这种情况可以解决吗

**Comment by johnsonlee** [comment]
> 那这种情况可以解决吗

需要定位到是什么原因

**Comment by WDevaloper** [comment]
这个问题我也经常遇到，我觉得有可能是缓存引起的问题，我每次clean项目，就会出现这个问题，希望能帮你定位问题。
