### ISSUE TITLE
使用了finalizer插件，仍然有一堆TimeoutException

### ISSUE THREAD

**Issue by scuzoutao** [didi/booster#134]
- Android Gradle plugin version 3.5.1
- Booster version 0.20.0
- Stack traces

toast插件是work的。。

![image](https://user-images.githubusercontent.com/15356395/72598251-65698a00-394a-11ea-8589-bc47b1174f1b.png)

堆栈类似：
`java.util.concurrent.TimeoutException: android.content.res.AssetManager.finalize() timed out after 120 seconds
    at android.content.res.AssetManager.destroy(AssetManager.java)
    at android.content.res.AssetManager.finalize(AssetManager.java:571)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:214)
    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:193)
    at java.lang.Thread.run(Thread.java:818)`

**Comment by johnsonlee** [comment]
dump 一下线程看看 *FinalizerWatchDogDaemon* 线程还在不在

**Comment by johnsonlee** [comment]
另外，Android 系统是什么版本？
