### ISSUE TITLE
组件化怎么配置呢，我在主app配置后不通过，非组件化的项目可以

### ISSUE THREAD

**Issue by buyaomiege** [didi/booster#149]
Please provide the following informations.

- System version

- Java version
1.8
- Gradle version
3.2.0
- Android Gradle plugin version
4.6
- Booster version
1.4.0
- Stack traces
Caused by: java.lang.NoSuchFieldError: ASCII

**Comment by neighbWang** [comment]
在组件化后的壳工程里面配置功能即可。你这边报什么错误呢？

**Comment by buyaomiege** [comment]
我就是按照您的办法配置的，同步的时候直接报ASCII，具体看
Caused by: java.lang.NoSuchFieldError: ASCII
	at com.android.build.gradle.BasePlugin.checkPathForErrors(BasePlugin.java:1026)
	at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:267)
	at com.android.build.gradle.AbstractAppPlugin.apply(AbstractAppPlugin.java:127)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:45)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:37)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at build_cgeifd8u6wrnmryefkerouorh.run(D:\AndroidProject\GB_QDCloudShop_Android_YunDianB\app\build.gradle:1)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 97 more

**Comment by johnsonlee** [comment]
粘一下代码看看

**Comment by buyaomiege** [comment]
```apply plugin: 'com.alibaba.arouter'
buildscript {
    ext {
        workbenchModuleAsApp = false
        qrcodeModuleAsApp=false
        pushModuleAsApp=false
        storeoperationModuleAsApp=false
        dashboardModuleAsApp=false
        userModuleAsApp=false
        compileSdkVersion = 28
        targetSdkVersion = 28
        minSdkVersion = 16
        buildToolsVersion = '28.0.3'
        versionName = '1.0.9'
        versionCode = 9
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        booster_version = '1.4.0'
        var = [
                constraintlayout: "androidx.constraintlayout:constraintlayout:1.1.3",
                appcompat       : "androidx.appcompat:appcompat:1.0.2",
                recyclerview    : "androidx.recyclerview:recyclerview:1.0.0",
                alpha           : "androidx.appcompat:appcompat:1.0.0-alpha1",
                material        : "com.google.android.material:material:1.0.0-rc01",
                junit           : "junit:junit:4.12",
                runner          : "com.android.support.test:runner:1.0.2",
                espresso        : "com.android.support.test.espresso:espresso-core:3.0.2",
                arouter         : "com.alibaba:arouter-compiler:1.2.2",
                butterknife     : "com.jakewharton:butterknife-compiler:10.1.0",
        ]
    }
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/umsdk/release' }
        maven { url 'https://oss.sonatype.org/content/repositories/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        //butterknife
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
        classpath 'com.bugtags.library:bugtags-gradle:latest.integration'
        //arouter
        classpath "com.alibaba:arouter-register:1.0.2"
        //资源混淆AndResGuard
//        classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.16'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin

        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version" // ①
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://dl.bintray.com/umsdk/release' }
        maven { url 'https://oss.sonatype.org/content/repositories/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



```

**Comment by buyaomiege** [comment]
我把booster_version改成1.3.1可以通过了,另外我下了https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp 和booster-task-resource-deredundancy 编译无法通过

**Comment by johnsonlee** [comment]
> booster-task-resource-deredundancy

可能是缓存的原因，clean 一下就好了

**Comment by ouyangpeng** [comment]
我这边也是编译失败。

![image](https://user-images.githubusercontent.com/5885735/88287743-51517b80-cd25-11ea-9f35-efd3d2d24202.png)

![image](https://user-images.githubusercontent.com/5885735/88287825-72b26780-cd25-11ea-9486-162c832ce852.png)

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\CodeForAndroid\Launcher_source\Launcher\app-camera\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app-camera'.
> ASCII

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app-camera'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:204)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:209)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:64)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:667)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:136)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:261)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:173)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
	at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:110)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:87)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:84)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:84)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:64)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:49)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchFieldError: ASCII
	at com.android.build.gradle.BasePlugin.checkPathForErrors(BasePlugin.java:790)
	at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:253)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:120)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:47)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
	at com.xtc.component.buildgradle.XTCComponentBuildPlugin.apply(XTCComponentBuildPlugin.groovy:45)
	at com.xtc.component.buildgradle.XTCComponentBuildPlugin.apply(XTCComponentBuildPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at build_b6jj0rykdygspgkyzyylgo5rr.run(C:\CodeForAndroid\Launcher_source\Launcher\app-camera\build.gradle:1)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 94 more


* Get more help at https://help.gradle.org

CONFIGURE FAILED in 10s

```

**Comment by ouyangpeng** [comment]
> 我把booster_version改成1.3.1可以通过了,另外我下了[https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp](https://github.com/boostersamples/app%EF%BC%8C%E4%BD%BF%E7%94%A8booster_version=1.4.0%EF%BC%8C%E5%90%8C%E6%97%B6%E9%9B%86%E6%88%90booster-task-compression-cwebp) 和booster-task-resource-deredundancy 编译无法通过

改成1.3.1 版本可以编译，但是didi的booster插件  根本没起效果

**Comment by johnsonlee** [comment]
升级到最新版本试试？你们项目中都用到了哪些 booster 的特性？

**Comment by ouyangpeng** [comment]
> 升级到最新版本试试？你们项目中都用到了哪些 booster 的特性？

就是用的最新的版本   ` ext.booster_version = '2.3.1' `
使用的booster特性是 
```
        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
```

然后出现这个错误的

**Comment by ouyangpeng** [comment]
@johnsonlee   你好，我的项目有组件化，然后昨天将所有打了Tag的版本试了下， 从v2.3.1版本到v1.3.1版本

只有v1.3.1版本的  没有报这个错误

但是好像  线程改名的功能  并没有应用起来，profile一下看CPU模块显示的线程名称  没有改成包名前缀的样子

**Comment by johnsonlee** [comment]
看起来是 guava 的版本导致的，参考 #171

**Comment by johnsonlee** [comment]
> > 我把booster_version改成1.3.1可以通过了,另外我下了[https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp](https://github.com/boostersamples/app%EF%BC%8C%E4%BD%BF%E7%94%A8booster_version=1.4.0%EF%BC%8C%E5%90%8C%E6%97%B6%E9%9B%86%E6%88%90booster-task-compression-cwebp) 和booster-task-resource-deredundancy 编译无法通过
> 
> 
> 
> 改成1.3.1 版本可以编译，但是didi的booster插件  根本没起效果

2.3.1 对线程优化做了很大的改进，可以尝试一下，另外，能提供一下 build/reports 目录下输出的报告吗？这有助于我们定位问题

**Comment by ouyangpeng** [comment]
> 看起来是 guava 的版本导致的，参考 #171

打印出来的 guava版本是  23.5

```
+--- com.android.tools.build:gradle-api:3.0.0
|              |    +--- com.android.tools.build:builder-model:3.0.0 (*)
|              |    \--- com.google.guava:guava:22.0 -> 23.5-jre (*)

```

**Comment by ouyangpeng** [comment]
> > > 我把booster_version改成1.3.1可以通过了,另外我下了[https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp](https://github.com/boostersamples/app%EF%BC%8C%E4%BD%BF%E7%94%A8booster_version=1.4.0%EF%BC%8C%E5%90%8C%E6%97%B6%E9%9B%86%E6%88%90booster-task-compression-cwebp) 和booster-task-resource-deredundancy 编译无法通过
> > 
> > 
> > 改成1.3.1 版本可以编译，但是didi的booster插件  根本没起效果
> 
> 2.3.1 对线程优化做了很大的改进，可以尝试一下，另外，能提供一下 build/reports 目录下输出的报告吗？这有助于我们定位问题

直接sync就崩溃，根本就没有build文件夹内容输出啊！！！

![image](https://user-images.githubusercontent.com/5885735/88637783-2f714380-d0ed-11ea-889f-2a14fb1aaecc.png)

**Comment by johnsonlee** [comment]
> > > > 我把booster_version改成1.3.1可以通过了,另外我下了[https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp](https://github.com/boostersamples/app%EF%BC%8C%E4%BD%BF%E7%94%A8booster_version=1.4.0%EF%BC%8C%E5%90%8C%E6%97%B6%E9%9B%86%E6%88%90booster-task-compression-cwebp) 和booster-task-resource-deredundancy 编译无法通过
> > > 
> > > 
> > > 改成1.3.1 版本可以编译，但是didi的booster插件  根本没起效果
> > 
> > 
> > 2.3.1 对线程优化做了很大的改进，可以尝试一下，另外，能提供一下 build/reports 目录下输出的报告吗？这有助于我们定位问题
> 
> 直接sync就崩溃，根本就没有build文件夹内容输出啊！！！
> 
> ![image](https://user-images.githubusercontent.com/5885735/88638001-795a2980-d0ed-11ea-8cf2-3d31e0f4cee5.png)

在命令行运行 `buildEnv` 呢？

**Comment by ouyangpeng** [comment]
> > > > > 我把booster_version改成1.3.1可以通过了,另外我下了[https://github.com/boostersamples/app，使用booster_version=1.4.0，同时集成booster-task-compression-cwebp](https://github.com/boostersamples/app%EF%BC%8C%E4%BD%BF%E7%94%A8booster_version=1.4.0%EF%BC%8C%E5%90%8C%E6%97%B6%E9%9B%86%E6%88%90booster-task-compression-cwebp) 和booster-task-resource-deredundancy 编译无法通过
> > > > 
> > > > 
> > > > 改成1.3.1 版本可以编译，但是didi的booster插件  根本没起效果
> > > 
> > > 
> > > 2.3.1 对线程优化做了很大的改进，可以尝试一下，另外，能提供一下 build/reports 目录下输出的报告吗？这有助于我们定位问题
> > 
> > 
> > 直接sync就崩溃，根本就没有build文件夹内容输出啊！！！
> > ![image](https://user-images.githubusercontent.com/5885735/88638001-795a2980-d0ed-11ea-8cf2-3d31e0f4cee5.png)
> 
> 在命令行运行 `buildEnv` 呢？



打印出来的 guava版本是 23.5

+--- com.android.tools.build:gradle-api:3.0.0
|              |    +--- com.android.tools.build:builder-model:3.0.0 (*)
|              |    \--- com.google.guava:guava:22.0 -> 23.5-jre (*)

**Comment by johnsonlee** [comment]
试试强制使用 `guava` 低版本：

```groovy
buildscript {

    ......

    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute(module("com.google.guava:guava"))
                    .with(module("com.google.guava:guava:23.0")) // 或者用 22.0
        }
    }
}
```

**Comment by ouyangpeng** [comment]
> 试试强制使用 `guava` 低版本：
> 
> ```groovy
> buildscript {
> 
>     ......
> 
>     configurations.all {
>         resolutionStrategy.dependencySubstitution {
>             substitute(module("com.google.guava:guava"))
>                     .with(module("com.google.guava:guava:23.0")) // 或者用 22.0
>         }
>     }
> }
> ```

还是不行的   

不过可能是我的build-tools和gradle版本太老导致，按照下面的 升级后   这个ASCII的问题不存在了。但是出现新问题，我先分析下新问题。

目前的配置是
```
classpath 'com.android.tools.build:gradle:3.0.0'
distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip
```

改成下面链接的配置。

>作者：焦糖玛奇朵AND卡布奇诺
链接：https://www.jianshu.com/p/93014a471d5e
来源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

```
gradle之前版本是3.2.0更新到最新，之后，就没有问题了
classpath 'com.android.tools.build:gradle:3.6.3'
同时，
gradle-wrapper.properties更新到5.6.4版本：
distributionUrl=https://services.gradle.org/distributions/gradle-5.6.4-all.zip
```
