### ISSUE TITLE
关于booster-transform-shrink移除常量的问题

### ISSUE THREAD

**Issue by DingProg** [didi/booster#17]
- 首先我接入 booster后，发现greenDao 不能正常运行，error log如下

```
Caused by: de.greenrobot.dao.DaoException: Could not init DAOConfig
        at de.greenrobot.dao.internal.DaoConfig.<init>(DaoConfig.java:94)
        at de.greenrobot.dao.AbstractDaoMaster.registerDaoClass(AbstractDaoMaster.java:44)
     Caused by: java.lang.NoSuchFieldException: TABLENAME
        at java.lang.Class.getField(Class.java:1601)
        at de.greenrobot.dao.internal.DaoConfig.<init>(DaoConfig.java:56)
```

- 查看 错误的代码  发现反射拿TABLENAME

        `    this.tablename = (String) daoClass.getField("TABLENAME").get(null);`

- 这个实体如下

```
public class NoteDao extends AbstractDao<Note, Long> {
    public static final String TABLENAME = "NOTE";
}
```

- 查看你们的booster-transform-shrink 忽略配置属性
booster.transform.shrink.ignores=android/*,androidx/*

- 添加我的配置属性
booster.transform.shrink.ignores={packagename}.dao.NoteDao  

**未生效**
**并问一下，移除产量的时候，配置可以采用混淆配置文件去默认配置吗？当然R文件除外**

**Comment by johnsonlee** [comment]
规则改成这样试试：

```
booster.transform.shrink.ignores={packagename.replace('.', '/')}/dao/NoteDao.class
```

**Comment by DingProg** [comment]
替换成
`booster.transform.shrink.ignores={packagename.replace('.', '/')}/dao/*`
可以了，建议在文档上注明，只能使用‘/’而不是'.,'或者组件里面做适配，感觉也可以

**Comment by johnsonlee** [comment]
嗯，下版在 `shrink transformer` 里做一下模式的兼容

**Comment by johnsonlee** [comment]
`Booster v0.3.2` is available
