### ISSUE TITLE
集成后编译错误，java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Hope0310** [didi/booster#20]
全部集成和只集成 booster-transform-lint 都报这个错误。

Caused by: java.lang.ArrayIndexOutOfBoundsException: 97
        at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2445)
        at org.objectweb.asm.ClassReader.createLabel(ClassReader.java:2461)
        at org.objectweb.asm.ClassReader.readStackMapFrame(ClassReader.java:3120)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1854)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at com.didiglobal.booster.transform.asm.AsmTransformer.transform(AsmTransformer.kt:27)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.transform(BoosterTransformInvocation.kt:161)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.access$transform(BoosterTransformInvocation.kt:38)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2$1.invoke(BoosterTransformInvocation.kt:119)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2$1.invoke(BoosterTransformInvocation.kt:38)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:61)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:39)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:118)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:38)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:117)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:38)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.doFullTransform$booster_gradle_plugin(BoosterTransformInvocation.kt:111)
        at com.didiglobal.booster.gradle.BoosterTransform.transform(BoosterTransform.kt:38)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

**Comment by johnsonlee** [comment]
能看到是处理哪个 jar 出现异常的吗？

**Comment by johnsonlee** [comment]
如果可以的话，最好提供这个 jar，以便于我们分析其内容有什么特别的

**Comment by Hope0310** [comment]
Log 里面没有，有什么方法可以找到吗？

**Comment by johnsonlee** [comment]
试试 `0.3.2-SNAPSHOT`，在 `repositories` 里加上：

```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

然后，在命令行加上 `-i` 选项（开启 INFO 级别的 log），找到以 `Transforming ` 开头的 log

**Comment by Hope0310** [comment]
Transforming /Users/hope/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.31/e652770b6416c6d85934086899ffed3eccd35813/kotlin-stdlib-jdk7-1.3.31.jar
Transforming /Users/hope/.gradle/caches/modules-2/files-2.1/io.reactivex.rxjava2/rxkotlin/2.3.0/37d8fb3406df28bfc84fa0234b11067931369bc5/rxkotlin-2.3.0.jar
Transforming /Users/hope/.gradle/caches/transforms-1/files-1.1/multitype-kotlin-3.4.4.aar/7f7280a113b278c455437eaeea3414e7/jars/classes.jar
Transforming /Users/hope/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.31/11289d20fd95ae219333f3456072be9f081c30cc/kotlin-stdlib-1.3.31.jar

> Task :app:transformClassesWithBoosterForRelease FAILED
:app:transformClassesWithBoosterForRelease (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 16.217 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithBoosterForRelease'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithBoosterForRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.doFullTransform$booster_gradle_plugin(BoosterTransformInvocation.kt:110)
        at com.didiglobal.booster.gradle.BoosterTransform.transform(BoosterTransform.kt:38)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at org.objectweb.asm.ClassReader.readVerificationTypeInfo(ClassReader.java:3169)
        at org.objectweb.asm.ClassReader.readStackMapFrame(ClassReader.java:3104)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1854)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at com.didiglobal.booster.transform.asm.AsmTransformer.transform(AsmTransformer.kt:27)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.transform(BoosterTransformInvocation.kt:164)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.access$transform(BoosterTransformInvocation.kt:37)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2$1.invoke(BoosterTransformInvocation.kt:120)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2$1.invoke(BoosterTransformInvocation.kt:37)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:60)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:38)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:119)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:37)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:117)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:37)

**Comment by johnsonlee** [comment]
试试加上 `booster.transform.lint.ignores=android/*,androidx/*,*/kotlin/*`，参考：https://github.com/didi/booster/blob/master/booster-transform-lint/README.md

**Comment by Hope0310** [comment]
ignore 了这么多还是编不过，新建个小工程依赖对应的库没问题
booster.transform.lint.ignores=android/*,androidx/*,*/kotlin/*,com/facebook/*,io/reactivex/*,com/squareup/*,org/jetbrains/*,com/squareup/haha/*,com/kakao/*,com/squareup/leakcanary/*,android/arch/*,com/google/*,com/google/android/*

**Comment by johnsonlee** [comment]
建了一个 demo 工程试了一下，貌似不是 kotkin 的问题，最好确认一下是不是某个依赖的库有问题？

**Comment by johnsonlee** [comment]
方便提供一下依赖树么？

 ```bash
./gradlew dependencies
```

**Comment by johnsonlee** [comment]
或者提供一个 sample 工程的 repo 地址，便于我们分析

**Comment by Hope0310** [comment]
我没办法创建出有问题的 sample，我也很无奈

**Comment by johnsonlee** [comment]
试试：

```bash
./gradlew clean && rm -rvf .gradle
```

**Comment by Hope0310** [comment]
还是不行

**Comment by TellH** [comment]
这个问题我们遇到过，是ASM的问题，asm在读取个别class文件时出错。如果项目开了desuger就没有这个问题了。

**Comment by johnsonlee** [comment]
有复现路径吗？

**Comment by Hope0310** [comment]
添加 android.enableD8.desugaring = true 仍然报错

**Comment by TellH** [comment]
> desugaring

添加这三个option，才会才desuger
android.enableD8=true
android.enableD8.desugaring=false
android.enableDesugar=true

**Comment by Hope0310** [comment]
这样设置确实可以编译过，但是放弃 D8 desugaring 使用旧的 Desugar 打包效率差很多

**Comment by johnsonlee** [comment]
哪些库了用 Java 8 的特性？

**Comment by johnsonlee** [comment]
试试 `v0.3.3-SNAPSHOT`，加了更详细的 log 便于定位具体是哪个类报错

**Comment by yrickwong** [comment]
> 这个问题我们遇到过，是ASM的问题，asm在读取个别class文件时出错。如果项目开了desuger就没有这个问题了。
评论区惊现华哥

**Comment by Hope0310** [comment]
问题找到了，依赖的旧版本华为 push sdk 里面有几个broken class file。
通过 Jetifier 转换 Jetpack 时报错发现问题出在这个 jar。

**Comment by snpmyn** [comment]
> > desugaring
> 
> 添加这三个option，才会开desuger
> android.enableD8=true
> android.enableD8.desugaring=false
> android.enableDesugar=true

我遇到的就是这个场景，debugger开启正常，关闭报错。请问你是怎么解决的？

**Comment by hwh1997** [comment]
请问最后是怎么解决的华为push转换失败的问题

**Comment by Hope0310** [comment]
> 请问最后是怎么解决的华为push转换失败的问题

反编译之后再重新编译
