### ISSUE TITLE
toast问题没有被修复，还存在。

### ISSUE THREAD

**Issue by isayWu** [didi/booster#229]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by isayWu** [comment]
以下是我友盟上的报错，系统版本:7.1.1

Process Name: 'com.geek.luck.calendar.app'
Thread Name: 'main'
Back traces starts.
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4238189 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:820)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:459)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:185)
	at android.app.ActivityThread.main(ActivityThread.java:6473)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
Back traces ends.
