### ISSUE TITLE
Toast StackOverflowError

### ISSUE THREAD

**Issue by donglua** [didi/booster#3]
```
E/CrashReport: java.lang.StackOverflowError: stack size 8MB
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
        at com.didiglobal.booster.android.widget.Toast.show(Toast.java:25)
```

Android Gradle Plugin：3.4.0
Gradle：5.2.1
Booster：0.1.1

**Comment by johnsonlee** [comment]
试试 `ext.booster_version = 0.1.2-SNAPSHOT`，在 repositories 里加上：

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

**Comment by donglua** [comment]
```0.1.2-SNAPSHOT``` 可以

**Comment by johnsonlee** [comment]
[Booster v0.1.2](../releases/tag/v0.1.2) has been released
