### ISSUE TITLE
带有加密的jar包会序列化不过java.lang.SecurityException: SHA1 digest error for ，求大神解答

### ISSUE THREAD

**Issue by jingyongxuan666** [didi/booster#303]
带有加密的jar包会序列化不过，jar包无法参与打包了，报错如下
`java.lang.SecurityException: SHA1 digest error for org/bouncycastle/asn1/ASN1OctetStringParser.class
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at com.didiglobal.booster.transform.util.TransformKt.readBytes(transform.kt:138)
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:239)
	at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:54)
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:239)
	at com.didiglobal.booster.transform.util.TransformKt.readBytes$default(transform.kt:136)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at com.joyratel.plugin.extension.CommonExtKt.doTransform$lambda-9$lambda-8(CommonExt.kt:221)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntryRequest.getPayloadStream(ZipArchiveEntryRequest.java:62)
	at com.didiglobal.booster.transform.util.TransformKt.readBytes$default(transform.kt:136)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:473)
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:239)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:54)
	at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry(ScatterZipOutputStream.java:99)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:54)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:473)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:473)
	at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator.lambda$createCallable$1(ParallelScatterZipCreator.java:229)
	at com.joyratel.plugin.extension.CommonExtKt.doTransform$lambda-9$lambda-8(CommonExt.kt:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)`

**Comment by johnsonlee** [comment]
Duplicate of #368
