### ISSUE TITLE
listSharedLibraries  命令执行报错

### ISSUE THREAD

**Issue by king-ma1993** [didi/booster#319]
Please provide the following informations.
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/77381352/167082638-16799337-498f-48e7-81fb-504775eb8c59.png">

- System version

- Java version
java 11
- Gradle version
https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
- Android Gradle plugin version
com.android.tools.build:gradle:4.2.1
- Booster version
booster 4.5.3
- Stack traces
Caused by: java.nio.file.NoSuchFileException: /Users/mayunlong/AndroidStudioProjects/TestGradle/TestPermission/build/intermediates/full_jar/debug/full.jar
        at com.myl.plugin.list.so.ListSoTask.run(ListSoTask.kt:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ... 94 more

**Comment by johnsonlee** [comment]
please try `4.11.0-alpha4`, the fix will be released with `4.11.0`

**Comment by BaeBae33** [comment]
same issue with 4.11.0 or 4.12.0

**Comment by BaeBae33** [comment]
same issue with 4.11.0 or 4.12.0
