### ISSUE TITLE
线程优化报NoClassDefFoundError错误

### ISSUE THREAD

**Issue by zhangyujiu** [didi/booster#414]
Please provide the following informations.

- System version 10

- Java version 1.8

- Gradle version 7.3.3

- Android Gradle plugin version 7.2.1

- Booster version 4.16.1

- Stack traces
```
FATAL EXCEPTION: main
Process: com.cashbird.app, PID: 2478
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/didiglobal/booster/instrument/ShadowThread;
	at com.applovin.impl.sdk.utils.j.a(SourceFile:31)
	at com.applovin.sdk.AppLovinInitProvider.safedk_AppLovinInitProvider_onCreate_2d489e5f0a53f332476aae8409a0dc6c(SourceFile:25)
	at com.applovin.sdk.AppLovinInitProvider.onCreate(Unknown Source:10)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2113)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2087)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7764)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by zhangyujiu** [comment]
通过init.gradle的集成方式才会有问题

**Comment by johnsonlee** [comment]
缺少 `booster-android-instrument-thread` 依赖
