### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by a3349384** [didi/booster#45]
集成后编译失败，产生了数以百计的如下错误日志：

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    android/aapt/pb/internal/ResourcesInternal$CompiledFile.mergeConfig(Lcom/android/aapt/ConfigurationOuterClass$Configuration;)V @38: invokevirtual
  Reason:
    Type 'com/android/aapt/ConfigurationOuterClass$Configuration' (current frame, stack[2]) is not assignable to 'com/google/protobuf/GeneratedMessageLite'
  Current Frame:
    bci: @38
    flags: { }
    locals: { 'android/aapt/pb/internal/ResourcesInternal$CompiledFile', 'com/android/aapt/ConfigurationOuterClass$Configuration' }
    stack: { 'android/aapt/pb/internal/ResourcesInternal$CompiledFile', 'com/android/aapt/ConfigurationOuterClass$Configuration$Builder', 'com/android/aapt/ConfigurationOuterClass$Confi
guration' }
  Bytecode:
    0x0000000: 2bc7 000b bb00 1f59 b700 20bf 2ab4 0025
    0x0000010: c600 282a b400 25b8 0026 a500 1e2a 2ab4
    0x0000020: 0025 b800 292b b600 2ac0 002b b600 2cc0
    0x0000030: 0028 b500 25a7 0008 2a2b b500 25b1
  Stackmap Table:
    same_frame(@12)
    same_frame(@56)
    same_frame(@61)

        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollectorKt$parseResEntry$header$1.invoke(RetainedSymbolCollector.kt:82)
        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollectorKt$parseResEntry$header$1.invoke(RetainedSymbolCollector.kt)
        at com.didiglobal.booster.aapt2.BinaryParser.parse(BinaryParser.kt:81)
        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollectorKt.parseResEntry(RetainedSymbolCollector.kt:81)
        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollectorKt.parseLayoutXml(RetainedSymbolCollector.kt:63)
        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollector.compute(RetainedSymbolCollector.kt:32)
        at com.didiglobal.booster.transform.shrink.RetainedSymbolCollector.compute(RetainedSymbolCollector.kt:20)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by johnsonlee** [comment]
麻烦提供 *Android Gradle Plugin* 版本，推荐使用：3.2.0

**Comment by a3349384** [comment]
> 麻烦提供 _Android Gradle Plugin_ 版本，推荐使用：3.2.0

3.4.1

**Comment by johnsonlee** [comment]
*Android Gradle Plugin* `3.4.1` 改动比较大，还未进行适配，试试用 `3.2.0`

**Comment by a3349384** [comment]
> _Android Gradle Plugin_ `3.4.1` 改动比较大，还未进行适配，试试用 `3.2.0`

经过漫长的等待，3.2.0终于下载好了。不过编译还有有问题哈，日志如下：

```
Caused by: java.lang.RuntimeException: java.util.zip.ZipException
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:47)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
        ... 119 more
Caused by: java.util.zip.ZipException
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.doFullTransform$booster_gradle_plugin(BoosterTransformInvocation.kt:110)
        at com.didiglobal.booster.gradle.BoosterTransform.transform(BoosterTransform.kt:51)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 155 more
Caused by: java.util.zip.ZipException
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:117)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:37)
Caused by: java.util.zip.ZipException: duplicate entry: META-INF/maven/javax.jmdns/jmdns/pom.xml
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:37)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:119)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$2.accept(BoosterTransformInvocation.kt:37)
```

**Comment by johnsonlee** [comment]
是通过 *Android Studio* 构建的还是通过命令行构建的？

**Comment by a3349384** [comment]
刚刚的问题是由于我这边自己的工程和android gradle3.2.0不兼容造成的，和Booster无关。

目前，在android gradle3.2.0环境下，Booster工作正常。

**Comment by johnsonlee** [comment]
[Fix aapt2 parsing issue for Android gradle plugin 3.4+](b237bc9c6c58313debfd13236f3d92189c910a7e)
