### ISSUE TITLE
 java.lang.SecurityException: SHA-256 digest

### ISSUE THREAD

**Issue by hellokai55** [didi/booster#465]
Please provide the following informations.

- System version
Mac mini
Apple M1
MacOS 14.4

- Java version
java 11

- Gradle version
7.5
- Android Gradle plugin version
7.4.2
- Booster version
4.16.3
- Stack traces
```
Execution failed for task ':app:transformClassesWithBoosterForAlpha'.
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.SecurityException: SHA-256 digest error for org/eclipse/paho/client/mqttv3/internal/websocket/WebSocketNetworkModule.class
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithBoosterForAlpha'.
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
2024-07-16T17:37:33.819+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
```
最近升级了神策的plugin:com.sensorsdata.analytics.android:android-gradle-plugin2从3.5.4到4.0.1结果就报错了；
而且是mqttv3这个库org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5；
将神策降级为原来的3.5.4版本又没有这个问题了...
能帮忙看看啥问题吗？

**Comment by johnsonlee** [comment]
Unable to reproduce in my local env, it would be better to provide a sample project to reproduce

**Comment by johnsonlee** [comment]
Duplication of https://github.com/didi/booster/issues/368
