### ISSUE TITLE
接入 booster 打包失败

### ISSUE THREAD

**Issue by DingProg** [didi/booster#6]
Android Gradle Plugin：com.android.tools.build:gradle:3.1.3
Gradle 版本：4.4.0
booster 版本：0.1.2

* What went wrong:
Execution failed for task ':app-boot:transformClassesWithBoosterForRelease'.
> kotlin.io.ByteStreamsKt.readBytes(Ljava/io/InputStream;)[B

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app-boot:transformClassesWithBoosterForRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: kotlin.io.ByteStreamsKt.readBytes(Ljava/io/InputStream;)[B
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:70)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:55)
        at com.didiglobal.booster.transform.util.TransformKt.transform(transform.kt:25)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$1.accept(BoosterTransformInvocation.kt:104)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1$1.accept(BoosterTransformInvocation.kt:29)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:103)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation$doFullTransform$1.accept(BoosterTransformInvocation.kt:29)
        at com.didiglobal.booster.gradle.BoosterTransformInvocation.doFullTransform$booster_gradle_plugin(BoosterTransformInvocation.kt:102)
        at com.didiglobal.booster.gradle.BoosterTransform.transform(BoosterTransform.kt:38)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

**Comment by johnsonlee** [comment]
麻烦提供以下信息：

- Gradle 版本
- Android Gradle Plugin 版本
- Kotin 版本

**Comment by johnsonlee** [comment]
看样子是 kotlin 版本太低，建议将 kotlin 升到 `1.2.*+` 或者 `1.3.*+`

**Comment by DingProg** [comment]
我项目本身并没有依赖kotlin，需要我怎么升级呢？

**Comment by johnsonlee** [comment]
可能是 Android Gradle Plugin 内置的 kotlin 版本较低，试试在 `buildscript` 中加上：

```groovy
buildscript {
    ext.kotlin_version = org.gradle.kotlin.dsl.KotlinDependencyExtensionsKt.embeddedKotlinVersion
}

dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}
```

**Comment by DingProg** [comment]
在 buildscript 中加上还是报错
直接升级了Gradle版本 4.4.0  ->  5.2.1 ，OK了

**Comment by johnsonlee** [comment]
看来问题已经解决了

**Comment by TellH** [comment]
我也遇到了这个问题，但项目里gradle的版本不能随便升。
```
fun InputStream.transform(transformer: (ByteArray) -> ByteArray): ByteArray {
    return transformer(this.readBytes())
}
```
这里的readBytes能不能换个api或者实现？

**Comment by johnsonlee** [comment]
> 我也遇到了这个问题，但项目里gradle的版本不能随便升。
> 
> ```
> fun InputStream.transform(transformer: (ByteArray) -> ByteArray): ByteArray {
>     return transformer(this.readBytes())
> }
> ```
> 这里的readBytes能不能换个api或者实现？

升 Gradle 版本不影响，只要不是升 Android Gradle Plugin 的版本就行，或者[升 kotlin 的版本](#issuecomment-487349216)

**Comment by TellH** [comment]
> > 我也遇到了这个问题，但项目里gradle的版本不能随便升。
> > ```
> > fun InputStream.transform(transformer: (ByteArray) -> ByteArray): ByteArray {
> >     return transformer(this.readBytes())
> > }
> > ```
> > 这里的readBytes能不能换个api或者实现？
> 
> 升 Gradle 版本不影响，只要不是升 Android Gradle Plugin 的版本就行，或者[升 kotlin 的版本](#issuecomment-487349216)

没法通过升级kotlin解决。升级gradle版本成本有点大，升一次遇到的问题一个接一个 😢 ，目前用的gradle版本是4.6，应该不算小众吧。

**Comment by johnsonlee** [comment]
试试 `ext.booster_version = '0.1.4-SNAPSHOT'`，另外，请在 `buildscript` 中加上：

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

**Comment by johnsonlee** [comment]
Booster `v0.1.4` is available
