### ISSUE TITLE
debug版本安装失败

### ISSUE THREAD

**Issue by snpmyn** [didi/booster#90]
Please provide the following informations.

- System version
Honor V9    DUK-TL30    EMUI版本9.0.1    Android版本9
- Java version
JRE 1.8.0
- Gradle version
5.1.1
- Android Gradle plugin version
3.4.2
- Booster version
0.22.0
- Stack traces
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithInstantRunForDevelopDebug'.
> com.android.build.api.transform.TransformException: java.lang.IllegalStateException: java.lang.IllegalStateException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 6s

**Comment by neighbWang** [comment]
请尝试使用Terminal命令是否可以安装成功 `./gradlew clean installDebug --stacktrace`, 如果失败，辛苦查看一下栈信息与 #41 是否一样.

**Comment by snpmyn** [comment]
你好！我的gradle里面创建的有构建变体。我通过 `gradlew clean installDevelopDebug --stacktrace` 安装成功了。但是运行闪退，提示：
java.lang.NoSuchFieldError: No static field META_DATA_FILE_PROVIDER_PATHS of type Ljava/lang/String; in class Lleakcanary/internal/LeakCanaryFileProvider; or its superclasses (declaration of 'leakcanary.internal.LeakCanaryFileProvider' appears in /data/app/com.lalala.lalala-OXZ5ZkMHMVgDSkv5lLoo4g==/base.apk!classes3.dex)
        at leakcanary.internal.LeakCanaryFileProvider.<clinit>(LeakCanaryFileProvider.kt:369)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7176)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6727)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618)
        at android.app.ActivityThread.access$2000(ActivityThread.java:268)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by snpmyn** [comment]
提示这个LeakCanary报错

**Comment by zjn0505** [comment]
Reproducible on booster-transform-shrink v.0.22.0 + LeakCanary v.2.0-beta-3
Added `booster.transform.shrink.ignores=leakcanary/internal/LeakCanaryFileProvider` in `gradle.properties` as workaround.

**Comment by johnsonlee** [comment]
> Reproducible on booster-transform-shrink v.0.22.0 + LeakCanary v.2.0-beta-3
> Added `booster.transform.shrink.ignores=leakcanary/internal/LeakCanaryFileProvider` in `gradle.properties` as workaround.

We're going to deprecate constant fields deletion feature in the next version

**Comment by snpmyn** [comment]
> > Reproducible on booster-transform-shrink v.0.22.0 + LeakCanary v.2.0-beta-3
> > Added `booster.transform.shrink.ignores=leakcanary/internal/LeakCanaryFileProvider` in `gradle.properties` as workaround.
> 
> We're going to deprecate constant fields deletion feature in the next version

What time? Thanks

**Comment by SusionSuc** [comment]
> > Reproducible on booster-transform-shrink v.0.22.0 + LeakCanary v.2.0-beta-3
> > Added `booster.transform.shrink.ignores=leakcanary/internal/LeakCanaryFileProvider` in `gradle.properties` as workaround.
> 
> We're going to deprecate constant fields deletion feature in the next version

agree

**Comment by johnsonlee** [comment]
please try the latest version `0.23.0-SNAPSHOT` or `0.23.0`

**Comment by snpmyn** [comment]
> please try the latest version `0.23.0-SNAPSHOT` or `0.23.0`

Thanks very much! Now it works.
